BirdBank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurants.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path
from .views import RestaurantListView, RestaurantDetailView,\
    RestaurantCreateView, RestaurantUpdateView, RestaurantDeleteView,\
    MyPostView

urlpatterns = [
    path('', RestaurantListView.as_view(), name='home'),
    path('create/', RestaurantCreateView.as_view(), name='create'),
    path('<slug:slug>/', RestaurantDetailView.as_view(), name='detail'),
    path('<slug:slug>/update', RestaurantUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete', RestaurantDeleteView.as_view(), name='delete'),
    path('dashboard/myposts/', MyPostView.as_view(), name='my_posts'),
]

restaurants/models.py
from django.db import models
from django.contrib.auth.models import User
from .snippets import generate_unique_slug, choices
from django.utils.text import slugify

class Restaurant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to='restaurants/')
    categories = models.CharField(max_length=120)
    location = models.CharField(max_length=120)
    price = models.IntegerField()
    vat = models.PositiveIntegerField(default=0)
    taste = models.PositiveIntegerField(choices=choices)
    persons = models.PositiveIntegerField(choices=choices)
    details = models.TextField()
    slug = models.SlugField(unique=True, blank=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    views = models.IntegerField(default=0,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def likes_count(self):
        return self.likes.count()

    def get_categories(self):
        cats = self.categories.split(',')
        return cats

    def save(self, *args, **kwargs):
        if self.slug:  # edit
            if slugify(self.title) != self.slug:
                self.slug = generate_unique_slug(Restaurant, self.title)
        else:  # create
            self.slug = generate_unique_slug(Restaurant, self.title)
        super().save(*args, **kwargs)

    def delete(self,*args, **kwargs):
        self.image.delete()
        super().delete(*args, **kwargs)



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:100]

restaurants/forms.py
from django import forms
from .models import Restaurant,Comment
from .snippets import choices

class RestaurantCreateForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Enter title'}))
    categories = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Categories separated by comma. Example: chinese,thai'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    location = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Location'}))
    price = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Price'}))
    vat = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control','placeholder':'Vat in %'}))
    taste = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),choices=choices)
    persons = forms.ChoiceField(widget=forms.Select(
        attrs={'class': 'form-control'}), choices=choices)
    details = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Restaurant
        fields = ['title','image','categories','location','price','vat','taste','persons','details']

restaurants/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import RestaurantCreateForm
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Restaurant, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages


class RestaurantListView(ListView):
    queryset = Restaurant.objects.all()
    paginate_by = 6
    template_name = 'restaurants/restaurant_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        cat = self.request.GET.get('cat')
        author = self.request.GET.get('author')
        if q:
            queryset = queryset.filter(
                Q(title__icontains=q) |
                Q(details__icontains=q)
            ).distinct()
        if cat:
            queryset = queryset.filter(categories__icontains=cat)

        if author:
            queryset = queryset.filter(user__username=author)
        return queryset

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        post_id = request.POST.get('unlike')
        post_id2 = request.POST.get('like')
        if post_id is not None:
            post = get_object_or_404(Restaurant, id=post_id)
            post.likes.remove(request.user)
        if post_id2 is not None:
            post_id2 = request.POST.get('like')
            post = get_object_or_404(Restaurant, id=post_id2)
            post.likes.add(request.user)
        return redirect('home')


class RestaurantDetailView(DetailView):
    queryset = Restaurant.objects.all()

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        comment = request.POST.get('comment')
        c_slug = request.POST.get('slug')
        if comment:
            if c_slug:
                post = get_object_or_404(Restaurant, slug=c_slug)
                comment = Comment.objects.create(
                    user=request.user, post=post, text=comment)
                comment.save()
                return redirect('detail', c_slug)
        return redirect('detail', c_slug)


class RestaurantCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'restaurants/restaurant_form.html'
    form_class = RestaurantCreateForm
    success_url = reverse_lazy('my_posts')
    success_message = "Post Created Successfully"

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        return super().form_valid(form)


class RestaurantUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = RestaurantCreateForm
    template_name = 'restaurants/restaurant_form.html'
    success_url = reverse_lazy('my_posts')
    success_message = "Post Updated Successfully"

    def get_queryset(self):
        return Restaurant.objects.filter(user=self.request.user)


class RestaurantDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    success_url = reverse_lazy('my_posts')
    success_message = "Post Deleted Successfully"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Restaurant.objects.filter(user=self.request.user)


class MyPostView(LoginRequiredMixin, ListView):
    template_name = 'restaurants/my_posts.html'

    def get_queryset(self):
        return Restaurant.objects.filter(user=self.request.user)

templates/restaurants/my_posts.html
{% extends 'base.html' %}
{% block widgets %}{% endblock widgets %}
{% block title %}{{ block.super }}| Dashboard{% endblock title %}
{% block content %}
<div class="row my-3 mb-5">
    <div class="col-md-12 mb-5">

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}

        <div class="card">
            <h5 class="card-header text-center">My All Posts</h5>
            <div class="card-body">
                {% if object_list %}
                <table class="table text-center">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Post</th>
                            <th scope="col">Category</th>
                            <th scope="col">Population</th>
                            <th scope="col">Score</th>
                            <th scope="col">Flight_Height</th>
                            <th scope="col">Likes</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in object_list %}
                        <tr>
                            <td><a href="{% url 'detail' obj.slug %}">{{ obj.title }}</a></td>
                            <td>{{ obj.categories }}</td>
                            <td>{{ obj.price }}</td>
                            <td>{{ obj.taste }}</td>
                            <td>{{ obj.persons }}</td>
                            <td>{{ obj.likes_count }}</td>
                            <td>
                                <a class="btn btn-warning btn-sm" href="{% url 'update' obj.slug %}" role="button">Edit</a>
                                <a class="btn btn-danger btn-sm" href="{% url 'delete' obj.slug %}" role="button">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p>You have not any post yet !! <a href="{% url 'create' %}">Create a new one..</a></p>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/restaurants/restaurant_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}| Delete {{object.title}}?{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-8 my-5">
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input class="btn btn-primary" type="button" value="Cancel" onclick="window.history.go(-1);" />
            <input class="btn btn-danger" type="submit" value="Confirm" />
        </form>
    </div>
    {% endblock content %}

templates/restaurants/restaurant_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}{{ block.super }}| {{ object.title }}{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-lg-8">
        <!-- Title -->
        <h1 class="mt-4">{{ object.title }}</h1>
        <!-- Author -->
        <p class="lead">
            by
            {% if object.user.get_full_name %}
            <a href="/?author={{ object.user }}">{{ object.user.get_full_name }}</a>
            {% else %}
            <a href="/?author={{ object.user }}">{{ object.user.username }}</a>
            {% endif %}
        </p>

        <hr>
        <!-- Date/Time -->
        <p>Posted on, {{ object.created_at|naturaltime }}</p>
        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{ object.image.url }}" alt="{{ object.title }}">
        <hr>

        <!-- Post Content -->
        <p class="lead">{{ object.details }}</p>
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td>Platter</td>
                    <td>{{ object.title }}</td>
                </tr>
                <tr>
                    <td>Category:</td>
                    <td>
                        {% for cat in object.get_categories %}
                        <a href="/?cat={{ cat }}">{{ cat }}</a>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td>Location</td>
                    <td>{{ object.location }}</td>
                </tr>
                <tr>
                    <td>Population</td>
                    <td>{{ object.price }} Total, percentage of survival {{ object.vat }}%</td>
                </tr>
                <tr>
                    <td>Flight_Height</td>
                    <td>{{ object.persons }} meters</td>
                </tr>
                <tr>
                    <td>Score</td>
                    <td>{{ object.taste }} out of 10</td>
                </tr>
                <tr>
                    <td>Likes</td>
                    <td>{{ object.likes_count }}</td>
                </tr>
            </tbody>
        </table>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
                <form action="." method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" name='slug' value="{{ object.slug }}">
                        <textarea name="comment" class="form-control" rows="3" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>

        <!-- Single Comment -->

        {% if object.comments.all %}
        {% for comment in object.comments.all %}
        <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle comment_pic" src="{{ comment.user.profile.image.url }}" alt="Image">
            <div class="media-body">
                <h5 class="mt-0">{{ comment.user.get_full_name }}</h5>
                <p>{{ comment.text }}<br>
                    <small><i class="far fa-clock"></i>&nbsp{{ comment.created_at }}</small>
                </p>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% endblock content %}

templates/restaurants/restaurant_form.html
{% extends 'base.html' %}
{% block title %}
{% if 'update' in request.path %}{{ block.super }}| Update post{% else %}{{ block.super }}| Create New post{% endif %}
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-8 my-4">
        <div class="card">
            <h5 class="card-header text-center">
                {% if 'update' in request.path %}
                Update Post
                {% else %}
                Create Post
                {% endif %}
            </h5>
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="csrfmiddlewaretoken" value="E808Wjd4G1h2eDTXkgoGbgy3XCbX3CSGa49ZgGCqC2kiZU4fEfKwIkFg966A1mZl">
                    <p><label for="id_title">Title:</label> <input type="text" name="title" class="form-control" placeholder="Enter title" required id="id_title"></p>
<p><label for="id_image">Image:</label> <input type="file" name="image" class="form-control-file" accept="image/*" required id="id_image"></p>
<p><label for="id_categories">Categories:</label> <input type="text" name="categories" class="form-control" placeholder="Categories separated by comma." required id="id_categories"></p>
<p><label for="id_location">Location:</label> <input type="text" name="location" class="form-control" placeholder="Enter Location" required id="id_location"></p>
<p><label for="id_price">Population:</label> <input type="number" name="price" class="form-control" placeholder="Enter Population" required id="id_price"></p>
<p><label for="id_vat">percent of survial:</label> <input type="number" name="vat" class="form-control" placeholder="in %" required id="id_vat"></p>
                    <button class="btn btn-secondary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>

    {% endblock content %}

templates/restaurants/restaurant_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}{{ block.super }}| Home{% endblock title %}
{% block content %}
<!-- Blog Entries Column -->
<div class="row">
  <div class="col-md-8 my-4">
    <!-- Blog Post -->
    <div class="row">
      {% if object_list %}
      {% for obj in object_list %}
      <div class="col-md-6">
        <div class="card mb-4">
          <img class="card-img-top" src="{{ obj.image.url }}" alt="Card image cap" style="height:160px">
          <div class="card-body">
            <h3 class="card-title">
              <a href="{% url 'detail' obj.slug %}">{{ obj.title }}</a>
            </h3>
            <p class="card-text">
              <div class="row">
                <div class="col-md-6">
                  <b>Population:</b> {{ obj.price|intcomma }} Tk
                </div>
                <div class="col-md-6">
                  <b>Likes:</b> {{ obj.likes_count }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <b>Score:</b> {{ obj.taste }} out of 10
                </div>
                <div class="col-md-6">
                  <b>Flight_Height:</b> {{ obj.persons }} meters
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <b>Category: </b>
                  {% for cat in obj.get_categories %}
                  <a href="?q={{ request.GET.q }}&cat={{ cat }}">{{ cat }}</a>
                  {% endfor %}
                </div>
              </div>
            </p>
            <a href="{% url 'detail' obj.slug %}" class="btn btn-secondary">Details</a>
            <div class="float-right user-icons">
              {% if obj in user_liked_posts %}
              <form action="{% url 'home' %}" id='like_form{{ obj.id }}' method="POST">
                {% csrf_token %}
                <input type="hidden" name="unlike" value="{{ obj.id }}">
                <a href="javascript:{}" onclick="document.getElementById('like_form{{obj.id}}').submit(); return false;">
                  <i class="fas fa-thumbs-up"></i></a>
              </form>
              {% else %}
              <form action="{% url 'home' %}" id='unlike_form{{ obj.id }}' method="POST">
                {% csrf_token %}
                <input type="hidden" name="like" value="{{ obj.id }}">
                <a href="javascript:{}" onclick="document.getElementById('unlike_form{{obj.id}}').submit(); return false;">
                  <i class="far fa-thumbs-up"></i></a>
              </form>
              {% endif %}
            </div>
          </div>
          <div class="card-footer text-muted">
            Updated: {{obj.updated_at|naturaltime}}, By
            <a href="?author={{ obj.user }}">{{ obj.user }}</a>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <P class="btn btn-warning ml-3">Sorry !! No post found...</P>
      {% endif %}
    </div>

    <!-- Pagination -->
    {% if is_paginated %}
    <ul class="pagination justify-content-center mb-4">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; Older</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="">&larr; Older</a>
      </li>
      {% endif %}

      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">Newer &rarr;</a>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </div>
  {% endblock content %}